apiVersion: v1
kind: Service
metadata:
  name: homics-db
spec:
  selector:
    role: db
  ports:
    - name: tcp
      protocol: TCP
      port: 1521
      targetPort: 1521
    - name: http
      port: 81
      nodePort: 30003
  type: NodePort
