# Application YAML configuration

# Change port for the monolith to 8090
server:
  port: 8090

spring:

  # Set-up datasource
  datasource:
    url: jdbc:h2:tcp://homics-db:1521/monodb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
