# Application YAML configuration

# Set port for gateway to 8080
server:
  port: 8080

spring:
  application:
    name: zuul-server

# Url used for restTemplate calls to the application user
app:
  user:
    url: http://user:9001

# Zuul routing
zuul:
  routes:
    monolith:
      path: /mono/**
      url: http://monolith:8090/mono/
    user:
      path: /user/**
      url: http://user:9001/user/
    stats:
      path: /stats/**
      url: http://stats:9002/stats/
    stock:
      path: /stock/**
      url: http://stock:9003/stock/
