version: '3'
services:
  # H2: to deploy the database
  homics-db:
    image: oscarfonts/h2:1.4.197
    container_name: homics-database
    expose:
      - "1521"
      - "81"
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - /tmp/data/homics-data:/opt/h2-data

  # Todo 3: Fill the gateway and user parts of the compose to deploy those microservices

  # Gateway
  gateway:

  # User
  user:



  # Todo Bonus: Deploy the full marketplace, add monolith / stats / stock

  # Kafka
  # Todo: uncomment below when you need to use Kafka (used by monolith / stats / stock)
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: homics-zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka:1.0.0
#    container_name: homics-kafka
#    hostname: kafka
#    expose:
#      - "9092"
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_NUM_PARTITIONS: 1
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
