# Enabling H2 Console
spring:

  # Set-up datasource
  datasource:
    url: jdbc:h2:tcp://homics-db:1521/stockdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

app:
  topic:
    stock: stock

server:
  port: 9003
