# Enabling H2 Console
server:
  port: 9002

spring:

  # Set-up datasource
  datasource:
    url: jdbc:h2:tcp://homics-db:1521/statsdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
