apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: homics/user-activity:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /user/internal/version
            port: 9001
          initialDelaySeconds: 3
          periodSeconds: 3
